### PR TITLE
removed dependency on joda-time

### PR DESCRIPTION
**Pull request by lenalebt**

### CODE REVIEW

**Comment by dehora** [comment]
Happy to see this; It's a good idea to remove dependencies from library, but just some comments 

- It seems to make a breaking change to interfaces so the project version needs to be bumped. It's a pre 1.0 version, so I'll leave it to the project owners what level they want to use to indicate this / @dr4ke616 

- ZonedDateTime might not be the right option. ZonedDateTime has timezone logic for things like DST which can result in reordering of dates. If I understand the intent of the code, it's to store/record state about dates for lease management purposes. That would suggest using a Instant or OffsetDateTime instead, but it's worth discussing why the code would or would not need to be timezone aware.

- Changing spec and scala versions look orthogonal to the date alterations and should be done in a different pr (those changes seem fine to me fwiw).

**Comment by lenalebt** [comment]
Hi Bill,
I was not aware of the DST logic. I am happy to change to something different, can you tell me what makes most sense here? If you want to, I can also move the version changes of the libs to another PR, that just did not seem too important for me because of only minor version bumps.

Cheers,
Lena

**Comment by dr4ke616** [comment]
Im also happy to see this, thanks @lenalebt.

I agree with what @dehora says about breaking interface changes, but being pre 1.0 version is that really a bad thing? I can bump the current `0.0.05` to `0.0.06`.

As for being timezone aware, with regard to `occurred_at` and `received_at` attribute in the `EventMetadata`, should this be timezone aware? However, with regard to having timezone awareness for lease management I wouldn't see the need, if anything it could even be a raw timestamp.

**Comment by dehora** [comment]
> but being pre 1.0 version is that really a bad thing? I can bump the current 0.0.05 to 0.0.06.

It depends on who's using it and what expectations have been set (eg this lib can break before v1). I'd suggest at lease a minor (Y) change for breaking a pre-1 interface.


> if anything it could even be a raw timestamp.

It could be but I'd discourage that in JSON, or at least think it through, as there's at least 3 ways to define a timestamp, (seconds, millis, floating point). The [guidelines](http://zalando.github.io/restful-api-guidelines/json-guidelines/JsonGuidelines.html#should-date-property-values-should-conform-to-rfc-3399) that oversee those dates suggest offsets rather than zones, so OffsetDateTime might be a good option, possibly Instant if the dates are normalised first.

**Comment by dr4ke616** [comment]
I'd say go with `OffsetDateTime` then.

**Comment by lenalebt** [comment]
Okay, Then I'll go for replacing every `ZonedDateTime` with `OffsetDateTime`. I think events should be timezone-aware.

**Comment by dr4ke616** [comment]
Cool, I can merge this in and make a release unless there is any other work you wish to add?

**Comment by lenalebt** [comment]
No, I'm fine :). Would appreciate a release, then I could add it to my ticket.

**Comment by dr4ke616** [comment]
Cool, ill merge it then, however there seems to be an issue with the Travis builds (something wierd happening with a `before_install` command).

Anyway, once it builds successfully, it will automatically deploy a snapshot. On success of that I will release a bumped version.

**Comment by dr4ke616** [comment]
@lenalebt version `0.0.06` is now released, and should be available soon

**Comment by lenalebt** [comment]
Awesome, thanks a lot!

**Comment by dr4ke616** [comment]
@lenalebt version `0.0.06` is now available. Have it compiling here against an application.

**Pull request merged**
